title: CSE-160 Docs
description: The official CSE-160 wiki. RTFM.
# theme: just-the-docs
color_scheme: dark
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

logo: "rgbcube.png"

minima:
  skin: dark

livereload: true
live_reload_host: 0.0.0.0

url: https://ucsc-cse-160.github.io/docs

callouts:
  warning:
    title: Warning!
    color: red
  
  tip:
      title: Tip!
      color: yellow

  note:
    title: Note!
    color: blue
