version: '3.8'

services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - ./docs:/srv/jekyll:delegated
    environment:
      - JEKYLL_ENV=development
      - JEKYLL_LIVERELOAD_HOST=0.0.0.0
